<a href="https://colab.research.google.com/github/nhuwynh07/THDeepLearning/blob/main/DL_Tuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
!pip install numpy

In [8]:

list=[1,2,3]
print(list)

[1, 2, 3]


In [10]:
import numpy as np
array=np.array(list)
print(array)
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3]
[1 2 3 4 5]


In [15]:
a=np.array([(1,2,3),(4,5,6)])
print(a)
print(a.shape)
print(a.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [20]:
b=np.zeros((2,2))
print(b)
c=np.ones((2,2))
print(c)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


In [27]:
g=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(g)
print(g.shape)
p=np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
print(p)
print(p.shape) #(3,1,3) -> (3 layer, 1 row, 3 col)
k=p.reshape(3,3,1)
print("reshape ",k)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
(3, 1, 3)
reshape /n [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


In [31]:
e=np.array([[1,2,3],[4,5,6]])
print(e.flatten())
j=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,22,12]]])
print(j.shape)
print(j.flatten())

[1 2 3 4 5 6]
(2, 2, 3)
[ 1  2  3  4  5  6  7  8  9 10 22 12]


In [35]:
m=np.array([1,2,3])
n=np.array([4,5,6])
print(np.hstack((m,n)))
print(np.vstack((m,n)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [45]:
print("Random 2-D")
print(np.random.randint(100, size=(3,3)))
print("Random 1-D")
print(np.random.randint(100, size=(3,)))
print("Random 3-D")
print(np.random.rand(3,3,3))


Random 2-D
[[18 88 54]
 [37 79 92]
 [18 37 66]]
Random 1-D
[98 40 42]
Random 3-D
[[[0.18601961 0.45965217 0.71726573]
  [0.23172612 0.1092766  0.92713852]
  [0.65014892 0.71906664 0.57160656]]

 [[0.21624523 0.44857412 0.3933577 ]
  [0.35043675 0.93357078 0.07940318]
  [0.18641728 0.32383978 0.53322477]]

 [[0.35953833 0.76876432 0.61440826]
  [0.21877295 0.24289173 0.5645864 ]
  [0.15385204 0.4201171  0.27267406]]]


In [46]:
print(np.random.normal(5,0.5,10))

[4.92081989 5.2303889  5.26207444 4.38226761 4.90941931 4.83019337
 4.61644718 4.0317206  4.80832269 5.13777389]


In [47]:
!pip install pandas

In [48]:

import pandas as pd
dulieuxettuyen = pd.read_csv("https://raw.githubusercontent.com/huynhhoc/DataAnalystDeepLearning/main/Data/dulieuxettuyendaihoc.csv")
print (dulieuxettuyen.head(10))

   STT   T1   L1   H1   S1   V1   X1   D1   N1   T2  ...   X6   D6   N6  GT  \
0    1  7.2  7.3  6.3  7.3  7.0  7.9  7.3  5.5  8.4  ...  6.6  7.6  5.9   F   
1    2  5.4  3.9  3.9  4.0  5.4  5.4  5.3  2.8  6.3  ...  6.6  6.1  4.4   M   
2    3  5.6  6.8  7.2  7.5  4.3  7.4  5.8  3.2  5.0  ...  7.9  8.1  4.6   M   
3    4  6.6  6.4  5.3  6.9  5.4  7.3  6.4  5.8  5.1  ...  7.1  7.3  7.4   M   
4    5  6.0  5.0  6.0  7.3  6.5  7.7  7.9  6.1  5.4  ...  6.1  7.5  7.2   M   
5    6  9.3  7.6  7.9  8.6  7.0  7.3  7.7  7.9  9.6  ...  5.7  8.0  7.8   M   
6    7  2.8  3.9  5.5  6.9  5.0  7.3  4.6  5.2  4.4  ...  6.6  6.0  6.0   F   
7    8  8.3  6.0  7.6  5.1  7.5  4.7  5.8  7.2  6.7  ...  7.1  6.8  7.0   F   
8    9  6.5  6.3  7.6  6.0  5.5  7.1  6.3  5.0  7.3  ...  9.1  7.9  6.1   F   
9   10  7.3  5.9  4.7  7.1  6.7  7.9  6.7  7.7  8.0  ...  6.4  6.1  7.8   F   

   DT   KV   DH1   DH2   DH3  KT  
0 NaN  2NT  3.25  3.25  4.50  A1  
1 NaN    1  6.00  4.00  3.50   C  
2 NaN    1  5.00  6.75  4

In [49]:
print (dulieuxettuyen.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 56 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   STT     100 non-null    int64  
 1   T1      100 non-null    float64
 2   L1      100 non-null    float64
 3   H1      100 non-null    float64
 4   S1      100 non-null    float64
 5   V1      100 non-null    float64
 6   X1      100 non-null    float64
 7   D1      100 non-null    float64
 8   N1      100 non-null    float64
 9   T2      100 non-null    float64
 10  L2      100 non-null    float64
 11  H2      100 non-null    float64
 12  S2      100 non-null    float64
 13  V2      100 non-null    float64
 14  X2      100 non-null    float64
 15  D2      100 non-null    float64
 16  N2      100 non-null    float64
 17  T3      100 non-null    float64
 18  L3      100 non-null    float64
 19  H3      100 non-null    float64
 20  S3      100 non-null    float64
 21  V3      100 non-null    float64
 22  X3 